on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        nixpkgs:
          - 7ad7702fa8b0d409aaf83eba8be1479b97823cdc
          - 434e36ab91be1454bcd4854878d683aaf50633f5
        nix-darwin:
          - 49b807fa7c37568d7fbe2aeaafb9255c185412f9
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: .
      - uses: actions/checkout@v4
        with:
          repository: NixOS/nixpkgs
          ref: ${{ matrix.nixpkgs }}
          fetch-depth: 1
          path: ./nix_path/nixpkgs
      - uses: actions/checkout@v4
        with:
          repository: LnL7/nix-darwin
          ref: ${{ matrix.nix-darwin }}
          fetch-depth: 1
          path: ./nix_path/darwin
      - run: ls -R "${GITHUB_WORKSPACE}"
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: ${{ github.workspace }}/nix_path:darwin-config=${{ github.workspace }}/configuration.nix
      - name: Resolve https://github.com/NixOS/nix/issues/10892
        # https://github.com/NixOS/nix/issues/10892#issuecomment-2600755196
        run: curl --proto '=https' --tlsv1.2 -sSf -L https://github.com/NixOS/nix/raw/master/scripts/sequoia-nixbld-user-migration.sh | bash -
      # https://github.com/cachix/install-nix-action/blob/5b8c65d4d79bb2d232054c72252fa78a29c36b8a/README.md#how-do-i-print-nixpkgs-version-i-have-configured
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Build `darwin-rebuild`
        run: nix-build '<darwin>' -A darwin-rebuild
      - name: Run `darwin-rebuild switch`
        run: ./result/bin/darwin-rebuild switch
      - name: Check if build fails as expected
        if: ${{ failure() && matrix.nixpkgs == '434e36ab91be1454bcd4854878d683aaf50633f5' }}
        run: echo 'Build fails'
